Rmove -O0 cflags
"-O0" is added for debug aim, but in arm64 it will lead to following
errors:

/env/nwork/warrior/build-dragonboard-410c-weeston-ivi/tmp/work-shared/dragonboard-410c/kernel-source/arch/arm64/include/asm/jump_label.h:38:2:
note: in expansion of macro 'asm_volatile_goto'
  asm_volatile_goto(
  ^~~~~~~~~~~~~~~~~
/env/nwork/warrior/build-dragonboard-410c-weeston-ivi/tmp/work-shared/dragonboard-410c/kernel-source/include/linux/compiler-gcc.h:120:38:
warning: asm operand 0 probably doesn't match constraints
 #define asm_volatile_goto(x...) do { asm goto(x); asm (""); } while (0)
                                      ^~~
/env/nwork/warrior/build-dragonboard-410c-weeston-ivi/tmp/work-shared/dragonboard-410c/kernel-source/arch/arm64/include/asm/jump_label.h:38:2:
note: in expansion of macro 'asm_volatile_goto'
  asm_volatile_goto(
  ^~~~~~~~~~~~~~~~~
/env/nwork/warrior/build-dragonboard-410c-weeston-ivi/tmp/work-shared/dragonboard-410c/kernel-source/include/linux/compiler-gcc.h:120:38:
error: impossible constraint in 'asm'
 #define asm_volatile_goto(x...) do { asm goto(x); asm (""); } while (0)
                                      ^~~

CONFIG_OPTIMIZE_INLINING has been enabled forcely to let gcc optimize the
kernel image's size by uninlining functions that have been marked 'inline'.
("__always_inline" is needed to make function a inline one)

It seems this change introduce the error above when using "-O0" together with
atomic_xxx().

See https://lkml.org/lkml/2019/3/20/63